### ISSUE TITLE
"GET /js/dev.js.map" Error (404): "Not found"

### ISSUE THREAD

**Issue by DracoTVGraphics** [chrisryanouellette/CasparCG-Guide-HTML-Template#1]
Hi Chris ... i'm testing your file project and I found error in chromium and http-server
Could you explain how to fix it?
Thanks

Chromium:
DevTools failed to parse SourceMap: http://localhost:8080/js/dev.js.map

http-server log
`[2020-06-30T12:57:45.872Z]  "GET /js/dev.js.map" Error (404): "Not found"

**Comment by chrisryanouellette** [comment]
Hey @DracoTVGraphics! The source map for the Widget ( dev.js.map ) is not provided so that is why it is not loading. You can safely ignore this unless you want to modify the widget's code. It looks like [this Stack Overflow question](https://stackoverflow.com/questions/35002087/disable-source-maps-in-chrome-devtools#:~:text=2%20Answers&text=Open%20Developer%20Tools%2C%20go%20to,under%20the%20%22Sources%22%20settings.&text=You%20can%20double%20click%20line,files%20to%20unminified%20output%20files.) shows how to disable source map loading if the error is annoying.
If you want to modify the Widget, you will need to follow the [Developer Setup instructions](https://github.com/chrisryanouellette/CasparCG_HTML_Widget#development-setup) on it's repo.

**Comment by chrisryanouellette** [comment]
Closing unless there is another issue with the maps.
